
# from config import get_connection
# from load_data import load_csv


# class DataAgent:


#     def __init__(self):
#         pass


#     def ingest_data(self):

#         result = load_csv()

#         return result
#     def execute_query(self, sql):

#        print("\nGenerated SQL:")
#        print(sql)

#        conn = get_connection()

#        cursor = conn.cursor()

#        cursor.execute(sql)

#        result = cursor.fetchall()

#        print("Database Result:")
#        print(result)

#        cursor.close()
#        conn.close()
#        if result and isinstance(result[0], tuple):
#            return float(result[0][0])

#        return result
"""
data_agent.py

Executes SQL generated by SQLGenerationAgent.
"""

from semantics import DataLoader


class DataAgent:
    """
    Executes SQL on Databricks.
    """

    def __init__(self):

        self.loader = DataLoader()

    def run(self, sql: str):

        print("\nExecuting SQL on Databricks...")
        print("-" * 60)
        print(sql)
        print("-" * 60)

        result = self.loader.execute(sql)

        return result